name: dnddichas
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.2.0
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  uuid: ^4.4.0
  http: ^1.2.1
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/
