// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChvXoIAudzTkqwXAsQsmgGf_y9AcRFyJ0',
    appId: '1:973818078815:web:5ac9cff5f8573da07cddea',
    messagingSenderId: '973818078815',
    projectId: 'dnd-spellbook-carlos',
    authDomain: 'dnd-spellbook-carlos.firebaseapp.com',
    storageBucket: 'dnd-spellbook-carlos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEazoLHR7_6Sik9WY8_MnvS9JZWwnctAM',
    appId: '1:973818078815:android:6486df91fe6ba6dd7cddea',
    messagingSenderId: '973818078815',
    projectId: 'dnd-spellbook-carlos',
    storageBucket: 'dnd-spellbook-carlos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDheTQCy3R5T976MrLUKTcIAiz0YXdTMRA',
    appId: '1:973818078815:ios:8f3ee310c43003c97cddea',
    messagingSenderId: '973818078815',
    projectId: 'dnd-spellbook-carlos',
    storageBucket: 'dnd-spellbook-carlos.firebasestorage.app',
    iosBundleId: 'com.example.dnddichas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDheTQCy3R5T976MrLUKTcIAiz0YXdTMRA',
    appId: '1:973818078815:ios:8f3ee310c43003c97cddea',
    messagingSenderId: '973818078815',
    projectId: 'dnd-spellbook-carlos',
    storageBucket: 'dnd-spellbook-carlos.firebasestorage.app',
    iosBundleId: 'com.example.dnddichas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChvXoIAudzTkqwXAsQsmgGf_y9AcRFyJ0',
    appId: '1:973818078815:web:ba859e2452ae5f447cddea',
    messagingSenderId: '973818078815',
    projectId: 'dnd-spellbook-carlos',
    authDomain: 'dnd-spellbook-carlos.firebaseapp.com',
    storageBucket: 'dnd-spellbook-carlos.firebasestorage.app',
  );
}
